spring:
  application.name: zookeeperdemo
  profiles.active: test
  #security:
  #  user:
  #    name: "user"
  #    password: "password"

  thymeleaf:
    cache: false
  
  pidfile: shared/tmp/pids/application.pid
  
  redis:
     host: 10.3.22.43
     port: 6379
     read-time-out: 100000
     write-time-out: 100000
  
#eureka: 
#  instance: 
#    leaseRenewalIntervalInSeconds: 10 
#    health-check-url-path: /actuator/health 
#  client: 
#    registryFetchIntervalSeconds: 5 
#    serviceUrl: 
#      defaultZone: ${EUREKA_SERVICE_URL:http://10.3.22.14:8761}/eureka/

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"  #<2>
#  endpoint:
#    health:
#      show-details: ALWAYS


server:
  port: 8521

rfd_oracle_rl_zookeeper_filename: '/pms.wltest.com/oracle_dev_rl'
rfd_seller_mysql_rl_zookeeper_filename: /pms.wltest.com/mysql_dev_rl
    
---
spring:
  profiles: test
  
  
  
---
spring:
  profiles: demo
  
  
 
---
spring:
  profiles: production
  
  thymeleaf:
    cache: false
    
server:
  port: 8251
  
rfd_oracle_rl_zookeeper_filename: /pms.wuliusys.com/oracle_prod_rl
rfd_seller_mysql_rl_zookeeper_filename: /pms.wuliusys.com/mysql_prod_rl