spring:
  application.name: zookeeperdemo
  profiles.active: production

  thymeleaf:
    cache: false
  
  pidfile: shared/tmp/pids/application.pid
  

server:
  port: 8521

rfd_oracle_rl_zookeeper_filename: '/pms.wltest.com/oracle_dev_rl'
rfd_seller_mysql_rl_zookeeper_filename: /pms.wltest.com/mysql_dev_rl
    
---
spring:
  profiles: test
  
  
  
---
spring:
  profiles: demo
  
  
 
---
spring:
  profiles: production
  
  thymeleaf:
    cache: false
    
server:
  port: 8251
  
rfd_oracle_rl_zookeeper_filename: /pms.wuliusys.com/oracle_prod_rl
rfd_seller_mysql_rl_zookeeper_filename: /pms.wuliusys.com/mysql_prod_rl